version: "3.9"

services:

  parser_app:
    build: .
    container_name: parser_app
    command: ['./start.sh']
    ports:
      - "8092:8092"
    networks:
      - custom

  db_parsers:
    image: postgres:16.1
    container_name: "parser_db"
    hostname: 'db'
    volumes:
      - data:/var/lib/postgresql/data/
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - custom

volumes:
  data:

networks:
  custom:
    driver: bridge